#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OurNet-BBSAgent
version:      1.61
version_from: BBSAgent.pm
installdirs:  site
requires:
    Test::More:                    0.32
    Net::Telnet:                   3.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
